server:
  port: 8080

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/products/**
        - id: category-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/categories/**
        - id: auth-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/auth/**
#          filters:
#            - StripPrefix=1